# Setup
title:               "Junsuu's"
tagline:             'Programming Blog'
description:         'Junior programmer Junsuu''s Blog who want to be a goooood Web Back-end developer'
url:                 https://junsuu.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Junsuu
  url:               https://twitter.com/mdo
  email:             jsp2151@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

remote_theme : poole/lanyon
